# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-04 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0007_auto_20180804_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='hood',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hood.Neighbourhood'),
        ),
    ]
