# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-04 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0009_auto_20180804_0922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighbourhood',
            options={'verbose_name_plural': 'Location'},
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='location',
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='loc',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('Zurich', 'Zurich'), ('Paris', 'Paris'), ('Munich', 'Munich'), ('Tokyo', 'Tokyo'), ('London', 'London'), ('Melbourne', 'Melbourne'), ('Sydney', 'Sydney'), ('Berlin', 'Berlin')], default=1, max_length=65),
            preserve_default=False,
        ),
    ]
