# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-04 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0012_post_hood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hood',
        ),
    ]
