# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-06 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0015_auto_20180804_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hood.Neighbourhood'),
            preserve_default=False,
        ),
    ]
